namespace Narser.Two.Parser.Utilities
{
    public enum TokenKind
    {
        None = 0x0,
        ExclamationMark = 0x1,
        QuestionMark = 0x2,
        DoubleQuote = 0x3,
        SingleQuote = 0x4,
        CurrencySign = 0x5,
        Dollar = 0x6,
        Euro = 0x7,
        Pound = 0x8,
        Hash = 0x9,
        Ampersand = 0xA,
        ForwardSlash = 0xB,
        Backslash = 0xC,
        Percent = 0xD,
        RightCurlyBrace = 0xE,
        LeftCurlyBrace = 0xF,
        RightParanthesis = 0x10,
        LeftParanthesis = 0x11,
        RightSquareBrace = 0x12,
        LeftSquareBrace = 0x13,
        Plus = 0x14,
        Hyphen = 0x15,
        Diacritical = 0x16,
        GraveAccent = 0x17,
        Asterisk = 0x18,
        Caret = 0x19,
        Tilde = 0x1A,
        Underscore = 0x1B,
        Colon = 0x1C,
        Semicolon = 0x1D,
        RightArrow = 0x1E,
        LeftArrow = 0x1F,
        Comma = 0x20,
        Dot = 0x21,
        Pipe = 0x22,
        Numerical = 0x23,
        Identifier = 0x24,
        Section = 0x25,
        OneHalf = 0x26,
        At = 0x27,
        Equals = 0x28,
        StringLiteral = 0x29,
        LineFeed = 0x30,
    }
}